title: " "
description: "About Me"
profile_image: /assets/img/profile.jpg
remote_theme: pages-themes/time-machine
plugins:
- jekyll-remote-theme 
#linkedin_username: alexcleveringa
#social links:
#  linkedin: alexcleveringa
#  url: https://www.linkedin.com/in/alexcleveringa/
#- name = github
#  url: https://github.com/amclever
#- name = email
#  url: alex.cleveringa@gmail.com
