title: Alex Cleveringa
logo: assets/img/Cleveringa_headshot_copy.jpg
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
linkedin_username: alexcleveringa
social links:
- name = LinkedIn
  url: https://www.linkedin.com/in/alexcleveringa/
- name = github
  url: https://github.com/amclever
- name = email
  url: alex.cleveringa@gmail.com
