title: Alex Cleveringa
logo: _assets/img/Cleveringa_headshot_copy.jpg
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
linkedin_username: alexcleveringa
social:
  linkedin: https://www.linkedin.com/in/alexcleveringa/
  github: https://github.com/amclever
  email: alex.cleveringa@gmail.com
